const vowels = { A: 5, E: 5, I: 3, O: 4, U: 4, Ä: 2, Ö: 2, Ü: 2 };
const consonants = {
  B: 3,
  C: 3,
  D: 2,
  F: 2,
  G: 2,
  H: 3,
  J: 2,
  K: 2,
  L: 2,
  M: 3,
  N: 3,
  P: 2,
  Q: 3,
  R: 3,
  S: 3,
  T: 3,
  V: 2,
  W: 2,
  X: 2,
  Y: 3,
  Z: 2,
};
const v = true;
const c = true;
const questionsRed = [
  "Abfälliger Ausdruck für Versicherungsvertreter",
  "Potenzmittel",
  "anderes Wort für Rülpser",
  "hoch prozentiger Cocktail",
  "Gerät beim Urologen",
  "anderes Wort für Kannibale",
  "Damenunterwäsche",
  "japanische Kampfsportart",
  "Name einer Motorradgang",
  "anderes Wort für Übergewicht",
  "anderes Wort für Kiffen",
  "Kosename für den/die Liebste/n",
  "Flirt App",
  "gefährliches Gift",
  "synthetische Partydroge",
  "anderes Wort für Wespentaille",
  "erogene Zone",
  "Beschäftigte/r einer Recyclingfirma",
  "Künstlername einer Domina",
  "Westernheld",
  "anderes Wort für Penisverlängerung",
  "anderes Wort für G-Punkt",
  "lateinischer Name für einen Gesäßmuskel",
  "James Bond Bösewicht",
  "italienische Weinsorte",
  "anderes Wort für Rotznase",
  "dumm wie Brot",
  "Erotiksender",
  "Figur aus Herr der Ringe",
  "anderes Wort für verrückt",
  "geschieht vor allem nachts",
  "gefährliches Monster",
  "indische Göttin",
  "Kneipe auf der Reeperbahn",
  "anderes Wort für Speeddating",
  "anderes Wort für Liebesnacht",
  "anderes Wort für Furz",
  "mittelalterliches",
  "Folterinstrument",
  "Kondommarke",
  "zwielichtige Gestalt",
  "anderes Wort für Hoden",
  "anderes Wort für Vibrator",
  "Sportart für Zombies",
  "anderes Wort für Samenbank",
  "Gestalt aus der griechischen Mythologie",
  "Titel eines Erotikfilms",
  "anderes Wort für Blasenschwäche",
  "Heavy Metal Band",
  "gefährliche Krankheit",
  "Onlineshop für Sexspielzeug",
  "Männermagazin",
  "neuartiges Gleitgel",
  "Stellung aus dem Kamasutra",
  "französisches Liebeslied",
  "etwas sehr Feuchtes",
  "anderes Wort für Zäpfchen",
  "anderes Wort für Dung",
  "polnischer Kraftausdruck",
  "anderes Wort für aphrodisiakum",
  "anderes Wort für Hautausschlag",
  "Fruchtbarkeitsritual",
  "abfälliges Wort für Politiker",
  "Kosewort für Busen",
];
const questionsBlack = [
  "Name eines Superhelden",
  "Fantasiewesen",
  "Gefährliche Spinnenart",
  "Titel eines Zauberspruchs",
  "Name eines Sterns",
  "Name eines Roboters",
  "Kuschelmonster",
  "Name eines Zaubertranks",
  "Fantasieplanet",
  "Name eines Weltraumtieres",
  "Abenteuerinsel",
  "Fantasieland",
  "Zeitmaschine",
  "Lustige Pudding-Sorte",
  "Name einer Vorspeise",
  "Außergewöhnliche Chips-Sorte",
  "Exotisches Gemüse",
  "Name eines neuen Getränks",
  "Besondere Pizza-Art",
  "Fantasie-Cocktail",
  "Süßigkeiten-Innovation",
  "Name eines Schokoriegels",
  "Käse-Sorte",
  "Extravagante Torte",
  "Fantasiebrot",
  "Lustiger Burgername",
  "Neues Haustier",
  "Fantasietier",
  "Lustige Vogelart",
  "Name eines Fisches",
  "Tropisches Tier",
  "Name einer Pflanzenart",
  "Fantasie-Schnecke",
  "Verrückte Katzenrasse",
  "Name eines Dinosauriers",
  "Fantasie-Baum",
  "Unterwasserwesen",
  "Lustige Hundezüchtung",
  "Name eines neuen Waldes",
  "Lustige Sportart",
  "Name einer Tanzbewegung",
  "Exotisches Hobby",
  "Titel eines Comedy-Films",
  "Fantasie-Beruf",
  "Name einer Spielekonsole",
  "Skurriles Möbelstück",
  "Ungewöhnliche Kopfbedeckung",
  "Name eines Monsters",
  "Titel eines Gedichts",
  "Mystischer Gegenstand",
  "Name eines Freizeitparks",
  "Witziges Transportmittel",
  "Name einer Stadt",
  "Verrücktes Hotel",
  "Mystischer Tempel",
  "Fantasie-Flughafen",
  "Lustige Zuglinie",
  "Tropischer Ort",
  "Mystisches Dorf",
  "Abenteuerhöhle",
  "Name eines Schlosses",
  "Lustiger Straßenname",
  "Fantasie-Schiff",
  "Skurriler Bahnhof",
  "Name einer Hütte im Wald",
  "Titel eines Actionfilms",
  "Name einer Buchreihe",
  "Fantasie-Musikgenre",
  "Mystischer Filmtitel",
  "Name eines Rock-Albums",
  "Fantasie-Band",
  "Titel eines Liebesfilms",
  "Titel einer TV-Serie",
  "Name eines Krimis",
  "Mystisches Musical",
  "Name eines Podcasts",
  "Titel einer Doku",
  "Lustige Ballade",
  "Name eines Roboters",
  "Lustige Erfindung",
  "Name eines neuen Elements",
  "Titel einer Entdeckung",
  "Lustiges Laborgerät",
  "Mystische Energiequelle",
  "Fantasie-Maschine",
  "Skurriles Experiment",
  "Mystisches Portal",
  "Lustiger Algorithmus",
  "Name eines Wissenschaftlers",
  "Fantasie-Satellit",
  "Mystischer Stromkreislauf",
  "Neues Möbelstück",
  "Lustiger Haushaltsgegenstand",
  "Skurriles Kleidungsstück",
  "Mystischer Hut",
  "Lustiges Buch",
  "Name einer Marke",
  "Lustige Verpackung",
  "Mystisches Gadget",
  "Neues Werkzeug",
  "Fantasie-Spielzeug",
  "Titel einer neuen App",
  "Lustiger Kalendername",
  "Fantasie-Kochgerät",
  "Historische Figur",
  "Mystischer König",
  "Name eines Zukunftsplaneten",
  "Fantasie-Kaiserin",
  "Mystische Dynastie",
  "Titel einer Legende",
  "Lustiges Zeitalter",
  "Skurriles Bauwerk",
  "Historisches Artefakt",
  "Abenteuerreiche Epoche",
  "Mystisches Dorf",
  "Fantasie-Krone",
  "Name eines Zeitalters",
];
const questionsBlue = [
  "Eine neue Sportart mit Bananen",
  "Ein außerirdisches Haustier",
  "Eine Beleidigung im Elbischen",
  "Eine Tanzrichtung für Roboter",
  "Eine neue Religion für Katzen",
  "Ein magischer Zauberspruch gegen Zahnschmerzen",
  "Eine Eissorte aus dem Weltall",
  "Ein peinlicher Kosename",
  "Eine Krankheit, die nur Einhörner bekommen",
  "Ein Cocktail, den keiner bestellen sollte",
  "Das Lieblingsessen von Vampiren",
  "Eine Modeerscheinung in Atlantis",
  "Der schlimmste Urlaubsort der Galaxie",
  "Ein Möbelstück aus der Zukunft",
  "Eine neue App für streitende Pärchen",
  "Ein Gebäck aus Transsilvanien",
  "Der Name eines nervigen Superhelden",
  "Ein Geheimcode unter Waschbären",
  "Ein verfluchter Zauberwald",
  "Ein Shampoo für Drachen",
  "Der Rufname eines außerirdischen Königs",
  "Ein Instrument, das man mit den Füßen spielt",
  "Eine schlechte Erfindung",
  "Ein Flirtwort auf Marsianisch",
  "Eine besonders gefährliche Käsesorte",
  "Ein Tier, das es (hoffentlich) nicht gibt",
  "Eine neue Olympiadisziplin",
  "Ein Zaubermittel gegen Montag",
  "Der Name eines missglückten Roboters",
  "Ein besonders lautes Gemüse",
  "Eine Party nur für Schnecken",
  "Der Name eines Geisterhauses",
  "Ein Trend aus der Zukunft",
  "Eine Beleidigung für einen Hexenbesen",
  "Das Lieblingsspiel von Yetis",
  "Eine Erfindung, die niemand braucht",
  "Eine neue Sprache für Fische",
  "Ein Cocktail mit Senf",
  "Ein Sport, den man im Schlaf spielt",
  "Eine Beleidigung, die sich nett anhört",
  "Eine neue Tanzart für Einhörner",
  "Ein besonders nerviger Klingelton",
  "Ein Käse mit Superkräften",
  "Der Name eines peinlichen Popstars",
  "Eine Zauberformel gegen Schnarchen",
  "Ein Tierschrei, den noch niemand kennt",
  "Eine besonders langsame Sportart",
  "Ein neuer Feiertag für Hamster",
  "Der Name eines vergessenen Planeten",
  "Ein Shampoo, das man besser nicht benutzt",
];
const questionsGreen = [
  "Ein besonders faules Haustier",
  "Ein Haustier, das nur bei Vollmond aktiv wird",
  "Ein Luxus-Spa für Hamster",
  "Ein Kommando für Papageien mit Attitüde",
  "Ein Katzenspielzeug, das plötzlich lebendig wird",
  "Eine Sprache, die nur Meerschweinchen verstehen",
  "Ein Haustier aus der Unterwelt",
  "Der Name eines berühmten Influencer-Hundes",
  "Eine Diät für dicke Goldfische",
  "Eine App für eifersüchtige Katzen",
  "Ein Superheld, der eigentlich nur ein Kaninchen ist",
  "Ein Hundetrick, den keiner versteht",
  "Eine Fernsehshow nur für Wellensittiche",
  "Ein Haustier mit Allergie gegen Menschen",
  "Ein Aquarienbewohner mit Starallüren",
  "Ein Modetrend für Schildkröten",
  "Ein Anti-Motz-Halsband für Katzen",
  "Der Traumberuf eines verwöhnten Pudels",
  "Ein Haustier, das heimlich zaubern kann",
  "Ein Nagetier mit Weltherrschafts-Plänen",
  "Der Lieblingspodcast eines Chihuahuas",
  "Ein Fitnessprogramm für Faultiere",
  "Ein mysteriöser Duftbaum für Terrarien",
  "Ein Reiseservice für verwöhnte Haustiere",
  "Ein Hamster, der lieber DJ wäre",
];
const disorderArr = (arr) => {
  return arr.sort(() => Math.random() - 0.5);
};
const getNewVowelsBag = () => {
  const pool = [];
  for (const vowel in vowels) {
    for (let i = 0; i < vowels[vowel]; i++) {
      pool.push(vowel);
    }
  }
  return disorderArr(pool);
};
const getNewConsonantsBag = () => {
  const pool = [];
  for (const consonant in consonants) {
    for (let i = 0; i < consonants[consonant]; i++) {
      pool.push(consonant);
    }
  }
  return disorderArr(pool);
};

const getAllQuestions = () => {
  return new Set([
    ...questionsBlack,
    ...questionsRed,
    ...questionsBlue,
    ...questionsGreen,
  ]);
};

export default {
  getAllQuestions,
  getNewConsonantsBag,
  getNewVowelsBag,
  disorderArr,
};
